In [4]:
import pandas as pd

dnkn = pd.read_csv("BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv")

In [5]:
dnkn.head()

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5

In [6]:
dnkn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             780 non-null    object
 1   Item                 780 non-null    object
 2   Calories             780 non-null    object
 3   Total Fat (g)        780 non-null    object
 4   Saturated Fat (g)    780 non-null    object
 5   Trans Fat (g)        780 non-null    object
 6   Cholesterol (mg)     780 non-null    object
 7   Sodium (mg)          780 non-null    object
 8   Carbs (g)            780 non-null    object
 9   Fiber (g)            780 non-null    object
 10  Sugars (g)           780 non-null    object
 11  Protein (g)          780 non-null    object
 12  Weight Watcher Pnts  780 non-null    object
dtypes: object(13)
memory usage: 79.3+ KB

In [7]:
dnkn.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [8]:
dnkn.duplicated().sum()

1

In [9]:
dnkn[dnkn.duplicated()]

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
760,Sandwiches,Ham and Cheese Rollups,280,13,6,0,40,1050,27,1,2,13,275

In [ ]:
Should they be removed from the dataset? Yes. Because it would affect the accuracy of 
the analysis.

In [10]:
dnkn.nunique()

Category                23
Item                   779
Calories                87
Total Fat (g)           50
Saturated Fat (g)       29
Trans Fat (g)            5
Cholesterol (mg)        37
Sodium (mg)            112
Carbs (g)              120
Fiber (g)                9
Sugars (g)             122
Protein (g)             32
Weight Watcher Pnts    362
dtype: int64

In [ ]:
How would you interpret this output? There are 23 unique categories and 779 unique 
items, along with a unique count of each nutritional variable.

In [11]:
dnkn['Category'].value_counts()

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Macchiato        42
Iced Cappuccino       42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

In [ ]:
The category includes both beverage and food with a total of 23 categories.

In [12]:
dnkn.describe(include='all')

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
count,780,780,780,780,780,780,780,780,780,780,780,780,780
unique,23,779,87,50,29,5,37,112,120,9,122,32,362
top,Hot Coffee,Ham and Cheese Rollups,170,0,0,0,0,180,35,0,0,4,5
freq,88,2,38,242,269,755,222,24,30,508,33,94,13

In [13]:
dnkn['Total Fat (g)'].unique()

array(['0', '12', '9', '6', '4.5', '3', '10', '11', '28', '30', '22',
       '21', '23', '14', '15', '20', '19', '16', '18', '25', '31', '27',
       '17', '37', '40', '5', '8', '35', '26', '13', '7', '\xa0', '4',
       '1', '0.5', '1.5', '2.5', '2', '3.5', '42', '33', '24', '36', '54',
       '29', '32', '34', '52', '41', '43'], dtype=object)

In [14]:
dnkn['Saturated Fat (g)'].unique()

array(['0', '6', '4.5', '3', '3.5', '2.5', '1.5', '4', '12', '14', '9',
       '10', '11', '7', '5', '8', '13', '18', '22', '17', '15', '\xa0',
       '0.5', '19', '21', '1', '2', '20', '16'], dtype=object)

In [15]:
dnkn['Trans Fat (g)'].unique()

array(['0', '1.5', '1', '0.5', '\xa0'], dtype=object)

In [16]:
dnkn['Cholesterol (mg)'].unique()

array(['0', '35', '25', '20', '15', '10', '50', '30', '40', '130', '100',
       '70', '105', '80', '55', '<5', '\xa0', '125', '45', '60', '185',
       '340', '180', '95', '65', '190', '360', '195', '265', '175', '220',
       '120', '200', '240', '205', '110', '115'], dtype=object)

In [17]:
dnkn['Sodium (mg)'].unique()

array(['20', '15', '10', '65', '45', '30', '5', '60', '320', '240', '160',
       '300', '310', '470', '450', '420', '150', '340', '290', '400',
       '390', '440', '280', '135', '380', '480', '270', '430', '460',
       '360', '200', '370', '190', '330', '250', '170', '220', '180',
       '130', '230', '125', '100', '115', '75', '350', '260', '120',
       '\xa0', '95', '70', '50', '25', '85', '55', '90', '140', '105',
       '110', '210', '510', '570', '630', '500', '750', '620', '80', '40',
       '35', '1020', '810', '1260', '1460', '600', '410', '840', '1060',
       '800', '820', '1170', '520', '540', '670', '640', '1200', '590',
       '1190', '1210', '1080', '1240', '1980', '1010', '650', '960',
       '1140', '1220', '1270', '900', '910', '1050', '980', '1500',
       '1120', '710', '550', '850', '490', '760', '970', '580', '1160',
       '700', '680'], dtype=object)

In [18]:
dnkn['Fiber (g)'].unique()

array(['0', '1', '2', '3', '4', '\xa0', '6', '5', '8'], dtype=object)

In [19]:
dnkn['Protein (g)'].unique()

array(['1', '0', '2', '10', '7', '5', '4', '6', '3', '8', '11', '9',
       '\xa0', '12', '16', '15', '14', '13', '27', '24', '37', '17', '19',
       '26', '21', '23', '18', '28', '33', '22', '25', '20'], dtype=object)

In [20]:
dnkn['Carbs (g)'].unique()

array(['0', '2', '1', '37', '27', '18', '112', '84', '56', '172', '129',
       '86', '113', '85', '31', '44', '57', '47', '63', '39', '55', '48',
       '36', '58', '33', '41', '34', '50', '40', '21', '42', '61', '43',
       '32', '52', '38', '59', '35', '45', '30', '49', '24', '176', '135',
       '95', '175', '134', '94', '180', '139', '97', '184', '142', '99',
       '141', '138', '183', '117', '88', '177', '160', '120', '80',
       '\xa0', '191', '147', '103', '195', '150', '105', '111', '83',
       '110', '13', '10', '7', '65', '64', '73', '70', '53', '71', '51',
       '87', '72', '66', '89', '82', '12', '9', '6', '26', '67', '5', '4',
       '46', '3', '28', '19', '17', '25', '23', '16', '15', '79', '78',
       '60', '11', '20', '54', '14', '69', '22', '75', '77', '29', '74',
       '68', '8', '92'], dtype=object)

In [21]:
dnkn1 = dnkn.copy()

In [22]:
dnkn1.head()

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5

In [26]:
food_items = [
    'Donuts',
    'Sandwiches',
    'Muffins',
    'Kolache',
    'Hash Browns',
    "Dunkin’ Bowls"
]

In [27]:
dnkn1 = dnkn1[dnkn1['Category'] != "Dunkin’ Bowls"].copy()

In [28]:
dnkn1['Category'].value_counts()

Category
Hot Coffee            88
Iced Coffee           63
Hot Latte             63
Iced Latte            63
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Macchiato        42
Iced Cappuccino       42
Iced Tea              33
Hot Chocolate         28
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Name: count, dtype: int64

In [29]:
dnkn1.duplicated().sum()

0

In [30]:
dnkn2 = dnkn1.copy()

In [31]:
dnkn2['Cholesterol (mg)'] = dnkn2['Cholesterol (mg)'].replace('<5', '5')

In [32]:
for col in dnkn2.select_dtypes(include='object').columns:
    dnkn2[col] = (
        dnkn2[col]
        .str.replace('\xa0', '', regex=False)
        .str.strip()
    )

In [33]:
for col in dnkn.columns:
    if dnkn2[col].dtype == 'object':
        print('\n', col)
        print(dnkn2[col].unique()[:50])

 Category
['Cold Brew Coffee' 'Coolatta' 'Frozen Coffee' 'Hot Americano'
 'Hot Cappuccino' 'Hot Chocolate' 'Hot Coffee' 'Hot Latte' 'Hot Macchiato'
 'Iced Americano' 'Iced Cappuccino' 'Iced Coffee' 'Iced Latte'
 'Iced Macchiato' 'Iced Tea' 'Dunkin’ Refreshers' 'Soft Serve']

 Item
['Cold Brew Coffee, Large' 'Cold Brew Coffee, Medium'
 'Cold Brew Coffee, Small' 'Cold Brew Coffee with Cream, Large'
 'Cold Brew Coffee with Cream, Medium'
 'Cold Brew Coffee with Cream, Small'
 'Cold Brew Coffee with Cream and Sugar, Large'
 'Cold Brew Coffee with Cream and Sugar, Medium'
 'Cold Brew Coffee with Cream and Sugar, Small'
 'Nitro Cold Brew Coffee, Medium' 'Nitro Cold Brew Coffee, Small'
 'Blue Raspberry Coolatta, Large' 'Blue Raspberry Coolatta, Medium'
 'Blue Raspberry Coolatta, Small' 'Vanilla Bean Coolatta, Large'
 'Vanilla Bean Coolatta, Medium' 'Vanilla Bean Coolatta, Small'
 'Pineapple Coolatta, Large' 'Pineapple Coolatta, Medium'
 'Pineapple Coolatta, Small'
 'Caramel Swirl Frozen Coffee with Cream, Large'
 'Caramel Swirl Frozen Coffee with Cream, Medium'
 'Caramel Swirl Frozen Coffee with Cream, Small'
 'Caramel Swirl Frozen Coffee with Skim Milk, Large'
 'Caramel Swirl Frozen Coffee with Skim Milk, Medium'
 'Caramel Swirl Frozen Coffee with Skim Milk, Small'
 'Caramel Swirl Frozen Coffee with Whole Milk, Large'
 'Caramel Swirl Frozen Coffee with Whole Milk, Medium'
 'Caramel Swirl Frozen Coffee with Whole Milk, Small'
 'French Vanilla Swirl Frozen Coffee with Cream, Large'
 'French Vanilla Swirl Frozen Coffee with Cream, Medium'
 'French Vanilla Swirl Frozen Coffee with Cream, Small'
 'French Vanilla Swirl Frozen Coffee with Skim Milk, Large'
 'French Vanilla Swirl Frozen Coffee with Skim Milk, Medium'
 'French Vanilla Swirl Frozen Coffee with Skim Milk, Small'
 'French Vanilla Swirl Frozen Coffee with Whole Milk, Large'
 'French Vanilla Swirl Frozen Coffee with Whole Milk, Medium'
 'French Vanilla Swirl Frozen Coffee with Whole Milk, Small'
 'Frozen Coffee with Cream, Large' 'Frozen Coffee with Cream, Medium'
 'Frozen Coffee with Cream, Small' 'Frozen Coffee with Skim Milk, Large'
 'Frozen Coffee with Skim Milk, Medium'
 'Frozen Coffee with Skim Milk, Small'
 'Frozen Coffee with Whole Milk, Large'
 'Frozen Coffee with Whole Milk, Medium' 'Frozen Dunkaccino, Large'
 'Frozen Dunkaccino, Medium' 'Frozen Dunkaccino, Small'
 'Frozen Vanilla Chai/Vanilla Spice, Large']

 Calories
['5' '120' '90' '60' '260' '190' '130' '460' '350' '230' '790' '590' '390'
 '340' '1120' '860' '610' '830' '650' '470' '880' '680' '490' '1110' '640'
 '780' '500' '370' '250' '550' '410' '930' '710' '510' '400' '' '1160'
 '890' '630' '720' '480' '360' '240' '530' '10' '70' '45' '170' '110'
 '160']

 Total Fat (g)
['0' '12' '9' '6' '4.5' '3' '40' '31' '22' '5' '11' '8' '35' '26' '17'
 '13' '14' '10' '7' '' '4' '1' '0.5' '23' '21' '15' '16' '1.5' '2.5' '2'
 '18' '3.5' '20' '19' '27']

 Saturated Fat (g)
['0' '6' '4.5' '3' '3.5' '2.5' '1.5' '22' '17' '12' '7' '18' '14' '9' '15'
 '10' '5' '' '0.5' '4' '19' '8' '21' '13' '11' '1']

 Trans Fat (g)
['0' '1.5' '1' '0.5' '']

 Cholesterol (mg)
['0' '35' '25' '20' '15' '10' '130' '100' '70' '40' '30' '105' '80' '55'
 '5' '' '125' '50' '45' '60']

 Sodium (mg)
['20' '15' '10' '65' '45' '30' '5' '60' '320' '240' '160' '290' '220'
 '180' '130' '280' '150' '230' '125' '200' '100' '115' '75' '350' '260'
 '120' '' '480' '370' '250' '430' '330' '95' '70' '50' '25' '85' '55'
 '135' '90' '170' '140' '105' '110' '190' '210' '510' '470' '340' '570']

 Carbs (g)
['0' '2' '1' '37' '27' '18' '112' '84' '56' '172' '129' '86' '113' '85'
 '180' '139' '97' '184' '142' '99' '141' '138' '183' '57' '117' '88' '59'
 '177' '134' '94' '160' '120' '80' '' '191' '147' '103' '195' '150' '105'
 '111' '83' '55' '110' '13' '10' '7' '48' '36' '24']

 Fiber (g)
['0' '3' '2' '' '1' '4']

 Sugars (g)
['0' '2' '1' '36' '27' '18' '110' '83' '55' '167' '125' '107' '80' '53'
 '172' '132' '92' '176' '135' '94' '175' '134' '169' '130' '91' '173'
 '133' '93' '108' '81' '54' '112' '84' '56' '111' '159' '119' '151' '113'
 '75' '' '181' '139' '97' '185' '142' '99' '98' '109' '82']

 Protein (g)
['1' '0' '2' '10' '7' '5' '8' '6' '11' '9' '3' '4' '' '12' '16' '15' '14'
 '13' '19' '18']

 Weight Watcher Pnts
['4' '5' '126' '93.5' '63' '300' '219.5' '150' '570' '433' '285' '950.5'
 '710.5' '469.5' '567' '420' '283' '1304' '1001' '708' '998.5' '779' '561'
 '1051' '812' '582.5' '1291' '999' '707' '995.5' '767' '550' '1049' '810'
 '580.5' '899' '680' '450' '604' '448' '302' '657.5' '491.5' '1094' '833'
 '597' '942' '703' '476' '']

In [34]:
import numpy as np

dnkn2 = dnkn2.replace('', np.nan)

In [35]:
dnkn2.isnull().sum()

Category               0
Item                   0
Calories               3
Total Fat (g)          3
Saturated Fat (g)      3
Trans Fat (g)          3
Cholesterol (mg)       3
Sodium (mg)            3
Carbs (g)              3
Fiber (g)              3
Sugars (g)             3
Protein (g)            3
Weight Watcher Pnts    3
dtype: int64

In [36]:
dnkn3 = dnkn2.dropna().copy()

In [37]:
dnkn3.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [38]:
numeric_columns = [
    'Calories',
    'Total Fat (g)',
    'Saturated Fat (g)',
    'Trans Fat (g)',
    'Cholesterol (mg)',
    'Sodium (mg)',
    'Carbs (g)',
    'Fiber (g)',
    'Sugars (g)',
    'Protein (g)',
    'Weight Watcher Pnts'
]

for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])

In [39]:
dnkn3.dtypes

Category                object
Item                    object
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

In [40]:
print("========== MISSING VALUES ==========")
print(dnkn3.isnull().sum())

print("\n========== DATA TYPES ==========")
print(dnkn3.dtypes)

print("\n========== DUPLICATE RECORDS ==========")
print("Duplicates:", dnkn3.duplicated().sum())

print("\n========== CATEGORY CHECK ==========")
print(dnkn3['Category'].value_counts())

print("\n========== SPECIAL VALUE CHECK ==========")
print("Cholesterol Values:")
print(dnkn3['Cholesterol (mg)'].unique())

print("\nTotal Fat Values:")
print(dnkn3['Total Fat (g)'].unique())

print("\n========== DATASET SHAPE ==========")
print(dnkn3.shape)

print("\n========== SUMMARY STATISTICS ==========")
print(dnkn3.describe().round(2))

========== MISSING VALUES ==========
Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

========== DATA TYPES ==========
Category                object
Item                    object
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

========== DUPLICATE RECORDS ==========
Duplicates: 0

========== CATEGORY CHECK ==========
Category
Hot Coffee            88
Iced Coffee           63
Hot Latte             63
Iced Latte            63
Frozen Coffee         47
Hot Macchiato         45
Iced Macchiato        42
Hot Cappuccino        42
Iced Cappuccino       42
Iced Tea              33
Hot Chocolate         28
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Name: count, dtype: int64

========== SPECIAL VALUE CHECK ==========
Cholesterol Values:
[  0  35  25  20  15  10 130 100  70  40  30 105  80  55   5 125  50  45
  60]

Total Fat Values:
[ 0.  12.   9.   6.   4.5  3.  40.  31.  22.   5.  11.   8.  35.  26.
 17.  13.  14.  10.   7.   4.   1.   0.5 23.  21.  15.  16.   1.5  2.5
  2.  18.   3.5 20.  19.  27. ]

========== DATASET SHAPE ==========
(599, 13)

========== SUMMARY STATISTICS ==========
       Calories  Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  \
count    599.00         599.00             599.00         599.00
mean     253.33           5.04               3.03           0.03
std      183.42           6.37               3.98           0.16
min        5.00           0.00               0.00           0.00
25%      130.00           0.00               0.00           0.00
50%      230.00           4.00               2.50           0.00
75%      340.00           8.00               4.50           0.00
max     1160.00          40.00              22.00           1.50

       Cholesterol (mg)  Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  \
count            599.00       599.00     599.00     599.00      599.00
mean              15.39       139.42      46.03       0.35       42.79
std               18.44       111.38      35.13       0.74       33.01
min                0.00         5.00       0.00       0.00        0.00
25%                0.00        60.00      25.00       0.00       23.50
50%               10.00       120.00      40.00       0.00       38.00
75%               25.00       190.00      63.00       0.00       57.00
max              130.00       750.00     195.00       4.00      185.00

       Protein (g)  Weight Watcher Pnts
count       599.00               599.00
mean          5.99               293.16
std           4.17               215.54
min           0.00                 4.00
25%           2.00               156.50
50%           6.00               266.00
75%           9.00               386.00
max          19.00              1352.00

In [41]:
dnkn3.to_csv('dnkn_clean.csv', index=False)

In [42]:
dnkn4 = pd.read_csv('dnkn_clean.csv')

In [43]:
dnkn4.head()

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0.0,0.0,0.0,0,20,0,0,0,1,4.0
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0.0,0.0,0.0,0,15,0,0,0,0,5.0
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0.0,0.0,0.0,0,10,0,0,0,0,5.0
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12.0,6.0,0.0,35,65,2,0,2,2,126.0
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9.0,4.5,0.0,25,45,1,0,1,2,93.5

In [ ]:
For Deliverable Two, I imported the Dunkin’ Donuts nutritional menu dataset into 
Python and checked the data for any errors that needed to be fixed. I reviewed the 
dataset for missing values, duplicates, categorical inconsistencies, unique values, 
and odd/special characters. In this assessment I found a duplicate record, some 
irrelevant food categories (this project was only about the beverages) and strange 
entries on some of the nutrition columns like “<5” and blank space characters.

So I made copies of the data before the cleaning so I wouldn't lose the data original. 
I took out food products, except drinks, and changed some values. I used ‘null’ to 
fill the missing data and then dropped the rows that contained missing data, then 
changed the nutrition columns to numeric type and checked the data to ensure that the 
cleaning processes worked.
    
In wrapping up, I verified that the cleaned data set had 599 rows and 13 columns left,
with no missing values or duplicates, and saved it as dnkn_clean.csv, then imported it
into Python as dnkn4 to see if it imported correctly.